package autenticacao;


/**
* autenticacao/Servico_AutenticacaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoAutenticacao.idl
* Sunday, November 30, 2014 3:42:31 PM BRST
*/

public interface Servico_AutenticacaoOperations 
{
  String autenticar_usuario (String usuario, String senha);
  String cadastrar_usuario (String usuario, String senha);
} // interface Servico_AutenticacaoOperations
