package autenticacao;


/**
* autenticacao/Servico_AutenticacaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoAutenticacao.idl
* Tuesday, December 2, 2014 8:28:38 PM BRST
*/

public interface Servico_AutenticacaoOperations 
{
  String autenticar_usuario (String usuario, String senha);
  String cadastrar_usuario (String usuario, String senha);
  boolean validar_token (String token);
} // interface Servico_AutenticacaoOperations
