package autenticacao;


/**
* autenticacao/Servico_Autenticacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoAutenticacao.idl
* Tuesday, December 2, 2014 8:28:38 PM BRST
*/

public interface Servico_Autenticacao extends Servico_AutenticacaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Servico_Autenticacao
