package autenticacao;


/**
* autenticacao/Servico_Autenticacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoAutenticacao.idl
* Monday, December 1, 2014 11:50:11 PM BRST
*/

public interface Servico_Autenticacao extends Servico_AutenticacaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Servico_Autenticacao
