package autenticacao;


/**
* autenticacao/Servico_Autenticacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServicoAutenticacao.idl
* Sunday, November 30, 2014 3:42:31 PM BRST
*/

public interface Servico_Autenticacao extends Servico_AutenticacaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Servico_Autenticacao
