package BoasVindas;


/**
* BoasVindas/Msg_Boas_VindasHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoasVindas.idl
* Sunday, November 30, 2014 2:48:21 PM BRST
*/

abstract public class Msg_Boas_VindasHelper
{
  private static String  _id = "IDL:BoasVindas/Msg_Boas_Vindas:1.0";

  public static void insert (org.omg.CORBA.Any a, BoasVindas.Msg_Boas_Vindas that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BoasVindas.Msg_Boas_Vindas extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BoasVindas.Msg_Boas_VindasHelper.id (), "Msg_Boas_Vindas");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BoasVindas.Msg_Boas_Vindas read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Msg_Boas_VindasStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BoasVindas.Msg_Boas_Vindas value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BoasVindas.Msg_Boas_Vindas narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BoasVindas.Msg_Boas_Vindas)
      return (BoasVindas.Msg_Boas_Vindas)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BoasVindas._Msg_Boas_VindasStub stub = new BoasVindas._Msg_Boas_VindasStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BoasVindas.Msg_Boas_Vindas unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BoasVindas.Msg_Boas_Vindas)
      return (BoasVindas.Msg_Boas_Vindas)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BoasVindas._Msg_Boas_VindasStub stub = new BoasVindas._Msg_Boas_VindasStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
