package BoasVindas;


/**
* BoasVindas/Msg_Boas_Vindas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoasVindas.idl
* Sunday, November 30, 2014 2:48:21 PM BRST
*/

public interface Msg_Boas_Vindas extends Msg_Boas_VindasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Msg_Boas_Vindas
