package BoasVindas;


/**
* BoasVindas/Msg_Boas_VindasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BoasVindas.idl
* Sunday, November 30, 2014 1:55:34 PM BRST
*/

public interface Msg_Boas_VindasOperations 
{
  String boas_vindas ();
} // interface Msg_Boas_VindasOperations
