// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package arquivos;

public final class ServicoArquivosRemotosServidor_Stub
    extends java.rmi.server.RemoteStub
    implements arquivos.ServicoArquivosRemotos, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_criarPasta_0;
    private static java.lang.reflect.Method $method_downloadArquivo_1;
    private static java.lang.reflect.Method $method_listaArquivos_2;
    private static java.lang.reflect.Method $method_listaDiretorios_3;
    private static java.lang.reflect.Method $method_uploadArquivo_4;
    
    static {
	try {
	    $method_criarPasta_0 = arquivos.ServicoArquivosRemotos.class.getMethod("criarPasta", new java.lang.Class[] {java.lang.String.class});
	    $method_downloadArquivo_1 = arquivos.ServicoArquivosRemotos.class.getMethod("downloadArquivo", new java.lang.Class[] {java.lang.String.class});
	    $method_listaArquivos_2 = arquivos.ServicoArquivosRemotos.class.getMethod("listaArquivos", new java.lang.Class[] {});
	    $method_listaDiretorios_3 = arquivos.ServicoArquivosRemotos.class.getMethod("listaDiretorios", new java.lang.Class[] {});
	    $method_uploadArquivo_4 = arquivos.ServicoArquivosRemotos.class.getMethod("uploadArquivo", new java.lang.Class[] {byte[].class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ServicoArquivosRemotosServidor_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of criarPasta(String)
    public void criarPasta(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_criarPasta_0, new java.lang.Object[] {$param_String_1}, 374587234794588253L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of downloadArquivo(String)
    public byte[] downloadArquivo(java.lang.String $param_String_1)
	throws java.io.IOException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_downloadArquivo_1, new java.lang.Object[] {$param_String_1}, 4361405773545167804L);
	    return ((byte[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.io.IOException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of listaArquivos()
    public arquivos.ListaArquivos listaArquivos()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_listaArquivos_2, null, 3712051423750423169L);
	    return ((arquivos.ListaArquivos) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of listaDiretorios()
    public arquivos.ListaArquivos listaDiretorios()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_listaDiretorios_3, null, -4493550328282653889L);
	    return ((arquivos.ListaArquivos) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of uploadArquivo(byte[], String)
    public void uploadArquivo(byte[] $param_arrayOf_byte_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_uploadArquivo_4, new java.lang.Object[] {$param_arrayOf_byte_1, $param_String_2}, -277212026213667971L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
