//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServicoArquivamentoPortBinding", Namespace="http://arquivamento/")]
public partial class ServicoArquivamentoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback criarUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback criarPastaOperationCompleted;
    
    private System.Threading.SendOrPostCallback loginOperationCompleted;
    
    private System.Threading.SendOrPostCallback downloadArquivoOperationCompleted;
    
    private System.Threading.SendOrPostCallback listarDiretoriosOperationCompleted;
    
    private System.Threading.SendOrPostCallback listarArquivosOperationCompleted;
    
    private System.Threading.SendOrPostCallback autenticarUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadArquivoOperationCompleted;
    
    /// <remarks/>
    public ServicoArquivamentoService() {
        this.Url = "http://localhost:8080/servicoarquivamento";
    }
    
    /// <remarks/>
    public event criarUsuarioCompletedEventHandler criarUsuarioCompleted;
    
    /// <remarks/>
    public event criarPastaCompletedEventHandler criarPastaCompleted;
    
    /// <remarks/>
    public event loginCompletedEventHandler loginCompleted;
    
    /// <remarks/>
    public event downloadArquivoCompletedEventHandler downloadArquivoCompleted;
    
    /// <remarks/>
    public event listarDiretoriosCompletedEventHandler listarDiretoriosCompleted;
    
    /// <remarks/>
    public event listarArquivosCompletedEventHandler listarArquivosCompleted;
    
    /// <remarks/>
    public event autenticarUsuarioCompletedEventHandler autenticarUsuarioCompleted;
    
    /// <remarks/>
    public event uploadArquivoCompletedEventHandler uploadArquivoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string criarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        object[] results = this.Invoke("criarUsuario", new object[] {
                    arg0,
                    arg1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincriarUsuario(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("criarUsuario", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndcriarUsuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void criarUsuarioAsync(string arg0, string arg1) {
        this.criarUsuarioAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void criarUsuarioAsync(string arg0, string arg1, object userState) {
        if ((this.criarUsuarioOperationCompleted == null)) {
            this.criarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncriarUsuarioOperationCompleted);
        }
        this.InvokeAsync("criarUsuario", new object[] {
                    arg0,
                    arg1}, this.criarUsuarioOperationCompleted, userState);
    }
    
    private void OncriarUsuarioOperationCompleted(object arg) {
        if ((this.criarUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.criarUsuarioCompleted(this, new criarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string criarPasta([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        object[] results = this.Invoke("criarPasta", new object[] {
                    arg0,
                    arg1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincriarPasta(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("criarPasta", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndcriarPasta(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void criarPastaAsync(string arg0, string arg1) {
        this.criarPastaAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void criarPastaAsync(string arg0, string arg1, object userState) {
        if ((this.criarPastaOperationCompleted == null)) {
            this.criarPastaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncriarPastaOperationCompleted);
        }
        this.InvokeAsync("criarPasta", new object[] {
                    arg0,
                    arg1}, this.criarPastaOperationCompleted, userState);
    }
    
    private void OncriarPastaOperationCompleted(object arg) {
        if ((this.criarPastaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.criarPastaCompleted(this, new criarPastaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string login([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        object[] results = this.Invoke("login", new object[] {
                    arg0,
                    arg1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginlogin(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("login", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endlogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void loginAsync(string arg0, string arg1) {
        this.loginAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void loginAsync(string arg0, string arg1, object userState) {
        if ((this.loginOperationCompleted == null)) {
            this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
        }
        this.InvokeAsync("login", new object[] {
                    arg0,
                    arg1}, this.loginOperationCompleted, userState);
    }
    
    private void OnloginOperationCompleted(object arg) {
        if ((this.loginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string downloadArquivo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        object[] results = this.Invoke("downloadArquivo", new object[] {
                    arg0,
                    arg1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindownloadArquivo(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("downloadArquivo", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddownloadArquivo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void downloadArquivoAsync(string arg0, string arg1) {
        this.downloadArquivoAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void downloadArquivoAsync(string arg0, string arg1, object userState) {
        if ((this.downloadArquivoOperationCompleted == null)) {
            this.downloadArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadArquivoOperationCompleted);
        }
        this.InvokeAsync("downloadArquivo", new object[] {
                    arg0,
                    arg1}, this.downloadArquivoOperationCompleted, userState);
    }
    
    private void OndownloadArquivoOperationCompleted(object arg) {
        if ((this.downloadArquivoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.downloadArquivoCompleted(this, new downloadArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string listarDiretorios([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("listarDiretorios", new object[] {
                    arg0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistarDiretorios(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listarDiretorios", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndlistarDiretorios(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void listarDiretoriosAsync(string arg0) {
        this.listarDiretoriosAsync(arg0, null);
    }
    
    /// <remarks/>
    public void listarDiretoriosAsync(string arg0, object userState) {
        if ((this.listarDiretoriosOperationCompleted == null)) {
            this.listarDiretoriosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarDiretoriosOperationCompleted);
        }
        this.InvokeAsync("listarDiretorios", new object[] {
                    arg0}, this.listarDiretoriosOperationCompleted, userState);
    }
    
    private void OnlistarDiretoriosOperationCompleted(object arg) {
        if ((this.listarDiretoriosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listarDiretoriosCompleted(this, new listarDiretoriosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string listarArquivos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("listarArquivos", new object[] {
                    arg0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistarArquivos(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listarArquivos", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndlistarArquivos(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void listarArquivosAsync(string arg0) {
        this.listarArquivosAsync(arg0, null);
    }
    
    /// <remarks/>
    public void listarArquivosAsync(string arg0, object userState) {
        if ((this.listarArquivosOperationCompleted == null)) {
            this.listarArquivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarArquivosOperationCompleted);
        }
        this.InvokeAsync("listarArquivos", new object[] {
                    arg0}, this.listarArquivosOperationCompleted, userState);
    }
    
    private void OnlistarArquivosOperationCompleted(object arg) {
        if ((this.listarArquivosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.listarArquivosCompleted(this, new listarArquivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string autenticarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        object[] results = this.Invoke("autenticarUsuario", new object[] {
                    arg0,
                    arg1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginautenticarUsuario(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("autenticarUsuario", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndautenticarUsuario(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void autenticarUsuarioAsync(string arg0, string arg1) {
        this.autenticarUsuarioAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void autenticarUsuarioAsync(string arg0, string arg1, object userState) {
        if ((this.autenticarUsuarioOperationCompleted == null)) {
            this.autenticarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautenticarUsuarioOperationCompleted);
        }
        this.InvokeAsync("autenticarUsuario", new object[] {
                    arg0,
                    arg1}, this.autenticarUsuarioOperationCompleted, userState);
    }
    
    private void OnautenticarUsuarioOperationCompleted(object arg) {
        if ((this.autenticarUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.autenticarUsuarioCompleted(this, new autenticarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://arquivamento/", ResponseNamespace="http://arquivamento/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void uploadArquivo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
        this.Invoke("uploadArquivo", new object[] {
                    arg0,
                    arg1,
                    arg2});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadArquivo(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadArquivo", new object[] {
                    arg0,
                    arg1,
                    arg2}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnduploadArquivo(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void uploadArquivoAsync(string arg0, string arg1, string arg2) {
        this.uploadArquivoAsync(arg0, arg1, arg2, null);
    }
    
    /// <remarks/>
    public void uploadArquivoAsync(string arg0, string arg1, string arg2, object userState) {
        if ((this.uploadArquivoOperationCompleted == null)) {
            this.uploadArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadArquivoOperationCompleted);
        }
        this.InvokeAsync("uploadArquivo", new object[] {
                    arg0,
                    arg1,
                    arg2}, this.uploadArquivoOperationCompleted, userState);
    }
    
    private void OnuploadArquivoOperationCompleted(object arg) {
        if ((this.uploadArquivoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadArquivoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void criarUsuarioCompletedEventHandler(object sender, criarUsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class criarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal criarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void criarPastaCompletedEventHandler(object sender, criarPastaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class criarPastaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal criarPastaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void downloadArquivoCompletedEventHandler(object sender, downloadArquivoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class downloadArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal downloadArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void listarDiretoriosCompletedEventHandler(object sender, listarDiretoriosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listarDiretoriosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listarDiretoriosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void listarArquivosCompletedEventHandler(object sender, listarArquivosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class listarArquivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal listarArquivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void autenticarUsuarioCompletedEventHandler(object sender, autenticarUsuarioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class autenticarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal autenticarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void uploadArquivoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
